name: test
on:
  workflow_run:
    workflows:
      - main
jobs:
  trigger-circleci:
    runs-on: ubuntu-20.04
    if: github.event.workflow_run.conclusion == 'success'
    steps:
        - uses: actions/download-artifact@v4
          with:
            name: github_ref-${{ github.event.workflow_run.id }}
            run-id: ${{ github.event.workflow_run.id }}
            github-token: ${{ secrets.GITHUB_TOKEN }}
        - name: Trigger circleci
          run: |
             printf '{"branch": "%s" ,"parameters": {"GHA_Meta":"run-tests"}}' $(cat github_ref) > req_body
             curl -X POST --location "https://circleci.com/api/v2/project/gh/sledzikowy/dnacenter-ansible/pipeline" \
                -H "Content-Type: application/json" \
                -H "Circle-Token: ${{ secrets.CCI_TOKEN }}" \
                -d "@req_body"
    #   - name: Trigger CircleCI
    #     id: trigger-circle-ci
    #     uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.2.0
    #     with:
    #       GHA_Meta: "run-tests"
    #     env:
    #       CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
